### ISSUE TITLE
We are using (1). Not reading references in pdf

### ISSUE THREAD

**Issue by aito123** [jmbuhr/bps-quarto-format#4]
Hello, thanks for this template. I notice that in the model pdf of this template in the following link: 

https://quarto-journals.github.io/biophysical-journal/

And when rendering the example in my computer, quarto is not incorporating the references.bib in the document. This could be seen in the first page when calling the citation `[@quarto]` it appears:

We are using (1).

This could bring future problems in including citations in this template.

Let me know if this is a bug.
Thanks

**Comment by jmbuhr** [comment]
Hi there, thank you for the clear description. This is not a bug, just the way that references are displayed in the Biophysical Journal. This is specified by a `csl` file (this one in out case: https://github.com/quarto-journals/biophysical-journal/blob/main/_extensions/bj/biophysical-journal.csl) but you can also override this by supplying your own (https://quarto.org/docs/reference/formats/pdf.html#references). You can download more csl files from here: https://www.zotero.org/styles

That said, the example sentence is indeed a bit misleading, given the citation style, so I will change it.
